/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/+not-found.temp`; params?: Router.UnknownInputParams; } | { pathname: `/course-detail`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/mark-attendance`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/attendance` | `/attendance`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/courses` | `/courses`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/context/AuthContext`; params?: Router.UnknownInputParams; } | { pathname: `/enroll-tabs/enrolled-courses`; params?: Router.UnknownInputParams; } | { pathname: `/enroll-tabs/attendance`; params?: Router.UnknownInputParams; } | { pathname: `/enroll-tabs/profile`; params?: Router.UnknownInputParams; } | { pathname: `/enroll-tabs/history`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/+not-found.temp`; params?: Router.UnknownOutputParams; } | { pathname: `/course-detail`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/mark-attendance`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/attendance` | `/attendance`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/courses` | `/courses`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/context/AuthContext`; params?: Router.UnknownOutputParams; } | { pathname: `/enroll-tabs/enrolled-courses`; params?: Router.UnknownOutputParams; } | { pathname: `/enroll-tabs/attendance`; params?: Router.UnknownOutputParams; } | { pathname: `/enroll-tabs/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/enroll-tabs/history`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/+not-found.temp${`?${string}` | `#${string}` | ''}` | `/course-detail${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/mark-attendance${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/attendance${`?${string}` | `#${string}` | ''}` | `/attendance${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/courses${`?${string}` | `#${string}` | ''}` | `/courses${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/context/AuthContext${`?${string}` | `#${string}` | ''}` | `/enroll-tabs/enrolled-courses${`?${string}` | `#${string}` | ''}` | `/enroll-tabs/attendance${`?${string}` | `#${string}` | ''}` | `/enroll-tabs/profile${`?${string}` | `#${string}` | ''}` | `/enroll-tabs/history${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/+not-found.temp`; params?: Router.UnknownInputParams; } | { pathname: `/course-detail`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/mark-attendance`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/attendance` | `/attendance`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/courses` | `/courses`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/context/AuthContext`; params?: Router.UnknownInputParams; } | { pathname: `/enroll-tabs/enrolled-courses`; params?: Router.UnknownInputParams; } | { pathname: `/enroll-tabs/attendance`; params?: Router.UnknownInputParams; } | { pathname: `/enroll-tabs/profile`; params?: Router.UnknownInputParams; } | { pathname: `/enroll-tabs/history`; params?: Router.UnknownInputParams; };
    }
  }
}
